name: Build and Release npm Package

on:
  workflow_dispatch: # Allows the workflow to be triggered manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify the version of Node.js

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build the package
        run: npm run build

      - name: Package the build
        run: npm pack
        id: pack # This step will create a tarball (e.g., your-package-name-1.0.0.tgz)

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: Release ${{ github.ref_name }}
          files: |
            ./react-charts-1.0.0-semantic-release.tgz